name: SSH Setup and Connections

on: 
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        set -x  # Enable debugging output
        echo "Setting up SSH..."
        
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        
        # Add the SSH private key to the id_ed25519 file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        # Add the server's public key to known_hosts
        echo "Adding server public key to known_hosts..."
        ssh-keyscan -H -p 2222 ${{ secrets.SERVER_SSH_IP }} >> ~/.ssh/known_hosts

        # Use ssh-agent to load the SSH key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

        # Debug: Show the private key contents and known hosts file
        cat ~/.ssh/id_ed25519
        cat ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        echo "Testing SSH Connection..."
        ssh -i ~/.ssh/id_ed25519 -p 2222 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_SSH_IP }} -v "echo SSH connection successful!"
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
