name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH and test Connection
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_SSH_PORT: 2222
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Setting up SSH..."

          # Ensure the .ssh directory exists
          mkdir -p ~/.ssh
          
          # Add the SSH private key
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Debug: Verify the private key exists
          ls -l ~/.ssh/id_rsa || echo "Private key not found"
          cat ~/.ssh/id_rsa || echo "Private key is empty or not accessible"

          # Add the server's SSH key to known_hosts to avoid prompt
          echo "Adding server to known_hosts..."
          ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts

          # Debug: Check if the known_hosts file was created
          ls -l ~/.ssh/known_hosts || echo "known_hosts file not found"
          cat ~/.ssh/known_hosts || echo "Failed to add server to known_hosts"

          # Test SSH connection
          echo "Testing SSH connection..."
          ssh -T -o StrictHostKeyChecking=no -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_SSH_IP "echo SSH connection successful!"

          echo "SSH connection established successfully!"
