name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        run: |
          echo "Setting up SSH..."

          # Check if the private key is available
          if [ -z "${SSH_PRIVATE_KEY}" ]; then
            echo "ERROR: SSH private key is not set"
            exit 1
          fi

          # Create SSH directory and set permissions
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the server to known_hosts to prevent SSH fingerprint prompt
          ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts

          # Debug SSH configuration and test connection
          echo "Testing SSH connection to $SERVER_SSH_IP..."
          ssh -vvv -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_SSH_IP "echo 'SSH connection successful!'"

      - name: Deploy to Tomcat server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
        run: |
          echo "Starting deployment to Tomcat server..."

          # Compress the build directory
          echo "Creating archive of build directory..."
          tar -czf build.tar.gz build/

          # Transfer the archive to the server
          echo "Uploading build archive..."
          scp -v -o StrictHostKeyChecking=no build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/tmp/

          # SSH into the server and deploy the app
          echo "Deploying application..."
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_SSH_IP << EOF
            echo "Stopping Tomcat..."
            sudo systemctl stop tomcat || echo "Tomcat not running"

            echo "Cleaning old files..."
            sudo rm -rf $TOMCAT_WEBAPPS_PATH/ROOT/* || echo "No files to clean"

            echo "Extracting new files..."
            sudo tar -xzf /tmp/build.tar.gz -C $TOMCAT_WEBAPPS_PATH/ROOT || exit 1

            echo "Starting Tomcat..."
            sudo systemctl start tomcat || exit 1

            echo "Deployment completed successfully!"
          EOF
