name: SSH Setup and Connection

on:
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "Setting up SSH..."
        
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        
        # Add the private key from GitHub Secrets
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        # Add the server's public key to known_hosts
        echo "Adding server public key to known_hosts..."
        ssh-keyscan -H -p 2222 182.183.2.96 >> ~/.ssh/known_hosts

        # Use ssh-agent to load the private key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

    - name: Test SSH Connection
      run: |
        echo "Testing SSH Connection..."
        ssh -i ~/.ssh/id_ed25519 -p 2222 -o StrictHostKeyChecking=no -o PreferredAuthentications=publickey root@182.183.2.96 -v
        echo "done done done"
      env:
        SERVER_SSH_IP: 182.183.2.96

    - name: Build and Deploy to Tomcat
      env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
      run: |
        echo "Starting deployment to Tomcat server..."
        
        # Step 1: Install dependencies and build the project
        echo "Building the project..."
        npm install
        npm run build

        # Step 2: Create a tarball of the build directory
        echo "Creating build archive..."
        tar -czf build.tar.gz build/

        # Step 3: Transfer the build archive to the server
        echo "Transferring build archive to the server..."
        scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/home/$SERVER_USER/build.tar.gz

        # Step 4: SSH into the server and deploy the application
        echo "Deploying application to Tomcat..."
        ssh -p 2222 -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_SSH_IP << EOF
          echo "
