name: Deploy to Tomcat Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "Setting up SSH..."
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H -p 2222 ${{ secrets.SERVER_SSH_IP }} >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

    - name: Test SSH Connection
      run: |
        echo "Testing SSH Connection..."
        ssh -p 2222 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_SSH_IP }} exit

    - name: Build application
      run: |
        echo "Building application..."
        npm install
        npm run build

    - name: Package build directory
      run: |
        echo "Packaging build directory..."
        if [ ! -d "build" ]; then
            echo "Error: build directory not found!"
            exit 1
        fi
        tar -czf build.tar.gz build

    - name: Deploy to Tomcat server
      env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
      run: |
        echo "Transferring build archive to the server..."
        scp -P 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/home/$SERVER_USER/

        echo "Deploying application to Tomcat..."
        ssh -p 2222 -t -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER_USER@$SERVER_SSH_IP << EOF
          echo "Stopping Tomcat server..."
          sudo systemctl stop tomcat

          echo "Cleaning up old files..."
          sudo rm -rf $TOMCAT_WEBAPPS_PATH/ROOT/*

          echo "Extracting new build files..."
          sudo tar -xzf /home/$SERVER_USER/build.tar.gz -C $TOMCAT_WEBAPPS_PATH/ROOT

          echo "Starting Tomcat server..."
          sudo systemctl start tomcat

          echo "Deployment completed successfully!"
        EOF
