name: Clear SSH and Deploy to Tomcat Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear SSH configuration
        run: |
          echo "Clearing previous SSH configurations..."
          
          # Remove old SSH keys and configuration
          rm -rf ~/.ssh
          
          # Ensure directory is recreated
          mkdir -p ~/.ssh
          
          # Clean known hosts if needed
          rm -f ~/.ssh/known_hosts
          
          echo "SSH configuration cleared."

      - name: Set up SSH key
        run: |
          echo "Setting up SSH private key..."
          
          # Add SSH private key from GitHub secrets
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Debug: Verify the private key file exists
          ls -l ~/.ssh/id_rsa || echo "Private key not found"
          
          # Add server to known_hosts and debug
          echo "Adding server to known_hosts..."
          ssh-keyscan -H 182.183.2.96 >> ~/.ssh/known_hosts 2>&1
          
          # Debug: Show contents of known_hosts
          cat ~/.ssh/known_hosts || echo "Known hosts not available"

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@182.183.2.96 "echo SSH connection successful!"

      # After SSH is working, continue with your Tomcat deployment steps
