name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ env.SERVER_SSH_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Tomcat server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
      run: |
        # Transfer the build archive to the server
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ env.SERVER_USER }}@${{ env.SERVER_SSH_IP }}:~/
        
        # SSH into the server and deploy the app
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 ${{ env.SERVER_USER }}@${{ env.SERVER_SSH_IP }} << 'EOF'
          # Stop Tomcat
          sudo systemctl stop tomcat
          # Clean up old files in the ROOT directory
          rm -rf ${{ env.TOMCAT_WEBAPPS_PATH }}/ROOT/*
          
          # Extract the new build files
          tar -xzf build.tar.gz -C ${{ env.TOMCAT_WEBAPPS_PATH }}/ROOT
          
          # Start Tomcat
          sudo systemctl start tomcat
        EOF
