name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "Debug: SERVER_SSH_IP is $SERVER_SSH_IP"

        # Create the SSH directory
        mkdir -p ~/.ssh

        # Save the private key
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the server's IP to known_hosts
        ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts
        echo "Debug: known_hosts content:"
        cat ~/.ssh/known_hosts

        # Test SSH connection with verbose output
        ssh -vvv -o StrictHostKeyChecking=no -o ConnectTimeout=10 <your-server-user>@$SERVER_SSH_IP echo "SSH connection established successfully!"

    - name: Deploy to Tomcat server
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
      run: |
        echo "Starting deployment..."

        # Transfer the build archive to the server
        scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build.tar.gz ${{ env.SERVER_USER }}@${{ env.SERVER_SSH_IP }}:~/

        # SSH into the server and deploy the app
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 -o UserKnownHostsFile=/dev/null ${{ env.SERVER_USER }}@${{ env.SERVER_SSH_IP }} << 'EOF'
          echo "Stopping Tomcat..."
          sudo systemctl stop tomcat

          echo "Cleaning up old files..."
          rm -rf ${{ env.TOMCAT_WEBAPPS_PATH }}/ROOT/*

          echo "Extracting new build files..."
          tar -xzf build.tar.gz -C ${{ env.TOMCAT_WEBAPPS_PATH }}/ROOT

          echo "Starting Tomcat..."
          sudo systemctl start tomcat
        EOF

        echo "Deployment completed!"
