name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH and test connection
      - name: Set up SSH and test connection
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts
          ssh -T -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_SSH_IP "echo 'SSH connection successful!'"

      # Step 3: Build the project (optional - depending on your project)
      - name: Build the project
        run: |
          echo "Building the project..."
          # Add your build steps here (e.g., npm build for a React app)
          # npm install
          # npm run build

      # Step 4: Deploy to Tomcat server
      - name: Deploy to Tomcat
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
        run: |
          echo "Starting deployment to Tomcat server..."

          # Create a tarball of the build directory
          echo "Creating build archive..."
          tar -czf build.tar.gz build/

          # Transfer the build archive to the server
          echo "Transferring build archive to the server..."
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/home/$SERVER_USER/

          # SSH into the server and deploy the app
          echo "Deploying app to Tomcat..."
          ssh -t -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_SSH_IP << EOF
            echo "Stopping Tomcat..."
            sudo systemctl stop tomcat

            echo "Cleaning up old files..."
            rm -rf $TOMCAT_WEBAPPS_PATH/ROOT/*

            echo "Extracting new build files..."
            tar -xzf build.tar.gz -C $TOMCAT_WEBAPPS_PATH/ROOT

            echo "Starting Tomcat..."
            sudo systemctl start tomcat

            echo "Deployment completed!"
          EOF
