name: Deploy to Tomcat Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch (adjust if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu 24.04 (as per GitHub Actions update)

    steps:
    # Step 1: Setup SSH keys for secure connection
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 2: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 3: Install dependencies and build the application
    - name: Build the project (if needed)
      run: |
        # If your project is a React or Node.js app, run the build command
        # Example: npm install && npm run build (adjust as needed)
        echo "Running build process..."
        npm install
        npm run build

    # Step 4: Check if build directory exists
    - name: Check if build directory exists
      run: |
        if [ ! -d "build" ]; then
          echo "Build directory does not exist!"
          exit 1
        fi

    # Step 5: Create a tarball of the build directory
    - name: Create build tarball
      run: |
        echo "Creating build tarball..."
        tar -czf build.tar.gz -C build .
        echo "Build arch
