name: SSH Setup and Deploy to Tomcat Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "Setting up SSH private key..."
          
          # Ensure .ssh directory exists
          mkdir -p ~/.ssh
          
          # Add SSH private key from GitHub secrets (Replace 'YOUR_PRIVATE_KEY' with the actual secret name)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add server to known_hosts
          echo "Adding server to known_hosts..."
          ssh-keyscan -H 182.183.2.96 >> ~/.ssh/known_hosts
          
          # Debugging: Show contents of known_hosts
          cat ~/.ssh/known_hosts || echo "Known hosts not available"

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@182.183.2.96 "echo SSH connection successful!"

      # You can add the Tomcat deployment steps after the SSH connection is verified
      - name: Deploy to Tomcat
        run: |
          echo "Starting Tomcat deployment..."
          # Your Tomcat deployment steps go here (e.g., copying WAR file, starting Tomcat, etc.)
