name: SSH Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Setting up SSH
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          # Use printf to properly handle the private key
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Use ssh-keyscan to add the server's public key to known_hosts
          ssh-keyscan -H ${{ secrets.SERVER_SSH_IP }} >> ~/.ssh/known_hosts

      # Step 3: Verify SSH Key (Print the key to check it's correctly set up)
      - name: Verify SSH Key
        run: cat ~/.ssh/id_ed25519

      # Step 4: Test SSH connection (with verbose output)
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -vvv -T -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_SSH_IP }}

      # Step 5: Run deployment commands
      - name: Run deployment commands
        run: |
          echo "Running deployment commands..."
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_SSH_IP }} << 'EOF'
          echo "Deploying application..."
          # Add your deployment commands here
          whoami
          ls -la /path/to/project
          EOF
