name: SSH Setup and Connection

on: 
  push:
    branches:
      - main

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        echo "Setting up SSH..."
        
        # Create .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        
        # Add the private key from GitHub Secrets
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        # Add the server's public key to known_hosts
        echo "Adding server public key to known_hosts..."
        ssh-keyscan -H -p 2222 182.183.2.96 >> ~/.ssh/known_hosts

        # Use ssh-agent to load the private key
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519

    - name: Test SSH Connection
      run: |
        echo "Testing SSH Connection..."
        ssh -i ~/.ssh/id_ed25519 -p 2222 -o StrictHostKeyChecking=no root@182.183.2.96 -v

      env:
        SERVER_SSH_IP: 182.183.2.96
