name: Deploy Build to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        # Install any necessary dependencies for your build process
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Build project
      run: |
        # Example build command; replace with your actual build process
        if [ ! -d "build" ]; then
          echo "Build directory does not exist!"
          exit 1
        fi
        echo "Creating build tarball..."
        tar -czf build.tar.gz -C build .

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 2222 $SERVER_SSH_IP >> ~/.ssh/known_hosts

    - name: Transfer build archive to the server
      run: |
        echo "Transferring build archive to the server..."
        scp -P 2222 build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/tmp/

    - name: Deploying application to Tomcat
      run: |
        echo "Deploying application to Tomcat..."
        ssh -p 2222 $SERVER_USER@$SERVER_SSH_IP << EOF
          echo "Stopping Tomcat server..."
          sudo systemctl stop tomcat
          
          echo "Cleaning up old files..."
          sudo rm -rf /opt/tomcat/apache-tomcat-9.0.97/webapps/ROOT/*
          
          echo "Extracting new build files..."
          sudo tar -xzf /tmp/build.tar.gz -C /opt/tomcat/apache-tomcat-9.0.97/webapps/ROOT
          
          echo "Starting Tomcat server..."
          sudo systemctl start tomcat
          
          echo "Deployment completed successfully!"
        EOF
