name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
       
        echo "Testing SSH connection to $SERVER_SSH_IP..."
        ssh -vvv -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o UserKnownHostsFile=/dev/null root@182.183.2.96 echo "SSH connection established successfully!"
    
    - name: Deploy to Server
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
      run: |
        echo "Starting deployment..."
        # Deploy steps here...
