name: SSH Deployment

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Setting up SSH
        run: |
          set -x  # Enable debugging output
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # Manually add the server public key to known_hosts
          # You can obtain this key from your local machine by running: ssh-keyscan -H <your-server-ip>
          echo "Adding server public key to known_hosts..."
          echo "<server-ip> ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICy9nZdkwqXwFC7F0j2Wu46BQ7KdrEkErIttZXn6Ae7h" >> ~/.ssh/known_hosts
          
          # Debugging: Show the private key contents and known hosts file
          cat ~/.ssh/id_ed25519
          cat ~/.ssh/known_hosts

      # Step 3: Test SSH connection
      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -v -T -p ${{ secrets.SERVER_SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_SSH_IP }}
          echo "SSH connection established successfully!"

      # Step 4: Run deployment commands on the server
      - name: Run deployment commands
        run: |
          echo "Running deployment commands..."
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SERVER_SSH_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_SSH_IP }} << 'EOF'
          echo "Deploying application..."
          # Add your deployment commands here
          whoami
          ls -la /path/to/project
          EOF

    env:
      SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}        # Set in GitHub Secrets
      SERVER_SSH_PORT: 2222                             # Port set to 2222
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}    # Set in GitHub Secrets
      SERVER_USER: ${{ secrets.SERVER_USER }}            # Set in GitHub Secrets
