name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH and test the connection
      - name: Set up SSH and test Connection
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_SSH_PORT: 2222  # Ensure this is the correct port for SSH
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts
          # Print debug information for troubleshooting
          echo "Debugging SSH setup..."
          cat ~/.ssh/id_rsa
          cat ~/.ssh/known_hosts
          # Test the SSH connection with the correct port
          ssh -T -o StrictHostKeyChecking=no -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_SSH_IP
          echo "SSH connection established successfully!"
