name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH and test Connection
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_SSH_PORT: 2222
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: root
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts
          echo "Testing SSH connection..."
          ssh -vvv -T -o StrictHostKeyChecking=no -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_SSH_IP
          echo "SSH connection established successfully!"

      - name: Deploy Application
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_SSH_PORT: 2222
          SERVER_USER: root
        run: |
          echo "Deploying application..."
          scp -P $SERVER_SSH_PORT -o StrictHostKeyChecking=no build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/tmp
          ssh -t -p $SERVER_SSH_PORT -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_SSH_IP << EOF
            echo "Stopping application..."
            sudo systemctl stop app
            echo "Deploying new build..."
            tar -xzf /tmp/build.tar.gz -C /path/to/deploy/
            echo "Starting application..."
            sudo systemctl start app
          EOF
