name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Debug: Ensure SERVER_SSH_IP is being passed correctly
        echo "Debug: SERVER_SSH_IP is $SERVER_SSH_IP"

        # Create SSH directory and add private key
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the server's IP to known_hosts to avoid interactive prompt
        ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts

        # Test SSH connection (optional, but helpful for debugging)
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@$SERVER_SSH_IP echo "SSH connection established successfully!"

    - name: Deploy to Tomcat server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
        TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
      run: |
        # Transfer the build archive to the server
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ env.SERVER_USER }}@${{ env.SERVER_SSH_IP }}:~/

        # SSH into the server and deploy the app
        ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_SSH_IP }} << EOF
          echo "Stopping Tomcat..."
          sudo systemctl stop tomcat

          echo "Cleaning up old files in the ROOT directory..."
          sudo rm -rf ${{ env.TOMCAT_WEBAPPS_PATH }}/ROOT/*

          echo "Extracting new files..."
          tar -xzf ~/build.tar.gz -C ${{ env.TOMCAT_WEBAPPS_PATH }}/ROOT

          echo "Starting Tomcat..."
          sudo systemctl start tomcat
          echo "Deployment complete!"
        EOF
