name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH and test the connection
      - name: Set up SSH and test Connection
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_SSH_PORT: 2222  # Ensure this is the correct port for SSH
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_SSH_IP >> ~/.ssh/known_hosts
          # Test the SSH connection with the correct port
          ssh -T -o StrictHostKeyChecking=no -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_SSH_IP
          echo "SSH connection established successfully!"

      # Step 3: Deploy the application to the Tomcat server
      - name: Deploy to Tomcat server
        env:
          SERVER_SSH_IP: ${{ secrets.SERVER_SSH_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          TOMCAT_WEBAPPS_PATH: ${{ secrets.TOMCAT_WEBAPPS_PATH }}
        run: |
          echo "Starting deployment to Tomcat server..."
          # Create a tarball of the build directory
          echo "Creating build archive..."
          tar -czf build.tar.gz build/
          # Transfer the build archive to the server
          echo "Transferring build archive to the server..."
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $SERVER_SSH_PORT build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/home/$SERVER_USER/
          # SSH into the server and deploy the app
          echo "Deploying app to Tomcat..."
          ssh -t -o StrictHostKeyChecking=no -o ConnectTimeout=60 -o UserKnownHostsFile=/dev/null -p $SERVER_SSH_PORT $SERVER_USER@$SERVER_SSH_IP << EOF
            echo "Stopping Tomcat..."
            sudo systemctl stop tomcat
            echo "Cleaning up old files..."
            rm -rf $TOMCAT_WEBAPPS_PATH/ROOT/*
            echo "Extracting new build files..."
            tar -xzf build.tar.gz -C $TOMCAT_WEBAPPS_PATH/ROOT
            echo "Starting Tomcat..."
            sudo systemctl start tomcat
            echo "Deployment completed!"
          EOF
