name: Deploy to Tomcat Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build the project (if needed)
      run: |
        # Assuming you're using npm (adjust according to your project type)
        npm install
        npm run build

    - name: Check if build directory exists
      run: |
        if [ ! -d "build" ]; then
          echo "Build directory does not exist!"
          exit 1
        fi

    - name: Create build tarball
      run: |
        echo "Creating build tarball..."
        tar -czf build.tar.gz -C build .
        echo "Build archive created successfully."

    - name: Check if build.tar.gz exists
      run: |
        if [ ! -f build.tar.gz ]; then
          echo "build.tar.gz does not exist!"
          exit 1
        fi

    - name: Transfer build archive to the server
      run: |
        echo "Transferring build archive to the server..."
        scp -P 2222 build.tar.gz $SERVER_USER@$SERVER_SSH_IP:/tmp/

    - name: Deploy application to Tomcat
      run: |
        echo "Deploying application to Tomcat..."
        ssh -p 2222 $SERVER_USER@$SERVER_SSH_IP << 'EOF'
          # Stop Tomcat server
          sudo systemctl stop tomcat

          # Clean up old files in the Tomcat ROOT directory
          sudo rm -rf /opt/tomcat/apache-tomcat-9.0.97/webapps/ROOT/*

          # Extract the new build files from the tarball
          sudo tar -xzf /tmp/build.tar.gz -C /opt/tomcat/apache-tomcat-9.0.97/webapps/ROOT/

          # Start Tomcat server
          sudo systemctl start tomcat
        EOF
        echo "Deployment completed successfully!"
