name: Deploy Build to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (if using React or similar)
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust to the version you need

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        # Build your project and create the build directory
        if [ ! -d "build" ]; then
          echo "Build directory does not exist, creating it..."
          npm run build  # Adjust this to the actual build command for your project
        fi
        echo "Creating build tarball..."
        tar -czf build.tar.gz -C build .

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 2222 182.183.2.96 >> ~/.ssh/known_hosts

    - name: Transfer build archive to the server
      run: |
        echo "Transferring build archive to the server..."
        echo root@182.183.2.96
        scp -P 2222 -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 build.tar.gz root@182.183.2.96:/tmp/

    - name: Deploying application to Tomcat
      run: |
        echo "Deploying application to Tomcat..."
        ssh -p 2222 root@182.183.2.96 << EOF
          echo "Stopping Tomcat server..."
          sudo systemctl stop tomcat
          
          echo "Cleaning up old files..."
          sudo rm -rf /opt/tomcat/apache-tomcat-9.0.97/webapps/ROOT/*
          
          echo "Extracting new build files..."
          sudo tar -xzf /tmp/build.tar.gz -C /opt/tomcat/apache-tomcat-9.0.97/webapps/ROOT
          
          echo "Starting Tomcat server..."
          sudo systemctl start tomcat
          
          echo "Deployment completed successfully!"
        EOF
